[package]
name = "ansible-lint-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.15"
serde_yaml = "0.9.34"

[[bin]]
name = "ansible-lint"  # Specify the new binary name here
path = "src/main.rs"